version: "3.5"

networks:
    private-network:
        name: docker-private-apps-network
        external: true

services:
    docker-private-web-server:
        image: docker-private-web-server:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 32M
            restart_policy:
                condition: on-failure
        networks:
            - private-network
