version: "3.5"

networks:
    public-network:
        name: docker-public-apps-network
        external: true
    private-network:
        name: docker-private-apps-network
        external: true

services:
    docker-public-db-and-cache-app:
        image: docker-public-db-and-cache-app:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 32M
            restart_policy:
                condition: on-failure
        networks:
            - public-network
            - private-network
        environment:
            - DB_APP_ENGINE=mysql
            - DB_APP_HOST=docker-private-mysql
            - DB_APP_PORT=3306
            - DB_APP_DATABASE=sample_database
            - DB_APP_USER=sample_user
            - DB_APP_PASSWORD=sample_user_password
