version: "3.5"

networks:
    public-network:
        name: docker-public-apps-network
        external: true
    private-network:
        name: docker-private-apps-network
        external: true

services:
    docker-public-sample-app:
        image: docker-public-sample-app:latest
        deploy:
            replicas: 3
            resources:
                limits:
                    cpus: "0.1"
                    memory: 32M
            restart_policy:
                condition: on-failure
        networks:
            - public-network
            - private-network
