version: "3.5"

networks:
    public-network:
        name: docker-public-apps-network
        external: true

services:
    docker-public-web-server:
        image: docker-public-web-server:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 32M
            restart_policy:
                condition: on-failure
            placement:
                constraints:
                    - node.role == manager
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./assets:/var/www/html/public/assets"
        networks:
            - public-network
