version: "3.5"

networks:
    private-network:
        name: docker-private-apps-network
        external: true

services:
    docker-private-mysql:
        image: docker-private-mysql:latest
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.1"
                    memory: 32M
            restart_policy:
                condition: any
        volumes:
            - "./databasedir:/var/lib/mysql"
        networks:
            - private-network
        environment:
            - MYSQL_ROOT_PASSWORD=mypass
        command: --default-authentication-plugin=mysql_native_password

#graphical ui for mysql
#    adminer:
#        image: adminer
#        restart: always
#        networks:
#            - private-network
#        ports:
#            - 8080:8080
